on: 
  push:
    branches:
      - master

name: Deploy to GoDaddy
jobs:
  web-deploy: 
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest from repo
      uses: actions/checkout@v3

    - name: FTP files to GoDaddy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.godaddy_ftp_host }}
        username: ${{ secrets.godaddy_ftp_user }}
        password: ${{ secrets.godaddy_ftp_pass }}
        server-dir: /
  
